<a href="https://colab.research.google.com/github/shravaniphalke805/Python-Libraries/blob/main/dataset_Special_task_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ecommerce_orders_dataset (2).csv to ecommerce_orders_dataset (2).csv

In [ ]:
# Load the dataset
df = pd.read_csv("ecommerce_orders_dataset (2).csv")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,...,Quantity,Unit_Price,Discount_%,Total_Amount,Payment_Method,Delivery_Days,Shipping_Type,Order_Status,Rating,Returned
0,7001,2025-10-31,C1000,Matthew Jones,52,Male,Mumbai,Maharashtra,Home,Chair,...,4,42959,0.0,171836.00,Cash,5,Standard,Shipped,1.0,Yes
1,7002,2026-01-17,C1001,Anthony Romero,45,Male,Indore,Madhya Pradesh,Beauty,Shampoo,...,1,16072,0.0,16072.00,UPI,2,Same Day,Delivered,5.0,No
2,7003,2025-07-18,C1002,Benjamin Davis,44,Male,Nagpur,Maharashtra,Electronics,Mouse,...,1,36781,5.0,34941.95,UPI,5,Express,Shipped,1.0,Yes
3,7004,2025-12-07,C1003,Becky Walker,21,Male,Indore,Madhya Pradesh,Home,Chair,...,5,46968,0.0,234840.00,Net Banking,6,Same Day,Processing,3.0,No
4,7005,2026-02-19,C1004,Laura Sanders,23,Female,Pune,Maharashtra,Beauty,Shampoo,...,3,16580,5.0,47253.00,Net Banking,3,Same Day,Processing,3.0,Yes

In [ ]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,...,Quantity,Unit_Price,Discount_%,Total_Amount,Payment_Method,Delivery_Days,Shipping_Type,Order_Status,Rating,Returned
95,7096,2025-08-12,C1095,Jessica Simpson,34,Female,Mumbai,Maharashtra,Beauty,Face Wash,...,5,38313,NaN,191565.00,Cash,3,Express,Cancelled,5.0,Yes
96,7097,2026-05-06,C1096,Jonathon Watts,57,Male,Pune,Maharashtra,Home,Lamp,...,1,29285,5.0,27820.75,Cash,7,Same Day,Cancelled,3.0,No
97,7098,2026-06-29,C1097,Ronnie Mann,58,Female,Indore,Madhya Pradesh,Electronics,Laptop,...,2,10088,10.0,18158.40,Net Banking,5,Express,Delivered,2.0,No
98,7099,2026-02-22,C1098,Gregory Brown,54,Female,Mumbai,Maharashtra,Fashion,Jacket,...,1,1760,0.0,1760.00,Cash,1,Same Day,Cancelled,5.0,Yes
99,7100,2025-08-21,C1099,Patrick Scott,41,Female,Pune,Maharashtra,Beauty,Face Wash,...,3,38906,5.0,110882.10,Card,2,Standard,Shipped,NaN,Yes

In [ ]:
df.shape

(100, 21)

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'State', 'Category', 'Product', 'Brand', 'Quantity',
       'Unit_Price', 'Discount_%', 'Total_Amount', 'Payment_Method',
       'Delivery_Days', 'Shipping_Type', 'Order_Status', 'Rating', 'Returned'],
      dtype='object')

In [ ]:
df.dtypes

Order_ID            int64
Order_Date         object
Customer_ID        object
Customer_Name      object
Age                 int64
Gender             object
City               object
State              object
Category           object
Product            object
Brand              object
Quantity            int64
Unit_Price          int64
Discount_%        float64
Total_Amount      float64
Payment_Method     object
Delivery_Days       int64
Shipping_Type      object
Order_Status       object
Rating            float64
Returned           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Order_Date      100 non-null    object
 2   Customer_ID     100 non-null    object
 3   Customer_Name   100 non-null    object
 4   Age             100 non-null    int64
 5   Gender          100 non-null    object
 6   City            100 non-null    object
 7   State           100 non-null    object
 8   Category        100 non-null    object
 9   Product         100 non-null    object
 10  Brand           100 non-null    object
 11  Quantity        100 non-null    int64
 12  Unit_Price      100 non-null    int64
 13  Discount_%      85 non-null     float64
 14  Total_Amount    100 non-null    float64
 15  Payment_Method  100 non-null    object
 16  Delivery_Days   100 non-null    int64
 17  Shipping_Type   100 non-null    object
 18  Order_Status    100 non-null    object
 19  Rating          79 non-null     float64
 20  Returned        100 non-null    object
dtypes: float64(3), int64(5), object(13)
memory usage: 16.5+ KB

In [ ]:
df.describe()

,Order_ID,Age,Quantity,Unit_Price,Discount_%,Total_Amount,Delivery_Days,Rating
count,100.000000,100.000000,100.000000,100.000000,85.000000,100.000000,100.00000,79.000000
mean,7050.500000,40.570000,3.070000,22407.520000,9.529412,62693.634500,3.92000,2.721519
std,29.011492,12.320021,1.401695,13931.954834,6.970325,49824.968958,2.01349,1.339122
min,7001.000000,18.000000,1.000000,488.000000,0.000000,488.000000,1.00000,1.000000
25%,7025.750000,31.750000,2.000000,10093.250000,5.000000,20627.400000,2.00000,2.000000
50%,7050.500000,43.000000,3.000000,22481.000000,10.000000,53264.400000,4.00000,3.000000
75%,7075.250000,50.000000,4.000000,32862.500000,15.000000,92508.500000,6.00000,4.000000
max,7100.000000,60.000000,5.000000,49919.000000,20.000000,234840.000000,7.00000,5.000000

In [ ]:
df.describe(include='all')

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,...,Quantity,Unit_Price,Discount_%,Total_Amount,Payment_Method,Delivery_Days,Shipping_Type,Order_Status,Rating,Returned
count,100.000000,100,100,100,100.000000,100,100,100,100,100,...,100.000000,100.000000,85.000000,100.000000,100,100.00000,100,100,79.000000,100
unique,NaN,87,100,100,NaN,2,5,2,4,13,...,NaN,NaN,NaN,NaN,4,NaN,3,4,NaN,2
top,NaN,2025-08-21,C1000,Matthew Jones,NaN,Male,Pune,Maharashtra,Beauty,Jeans,...,NaN,NaN,NaN,NaN,UPI,NaN,Same Day,Shipped,NaN,Yes
freq,NaN,4,1,1,NaN,52,24,83,31,17,...,NaN,NaN,NaN,NaN,30,NaN,34,30,NaN,59
mean,7050.500000,NaN,NaN,NaN,40.570000,NaN,NaN,NaN,NaN,NaN,...,3.070000,22407.520000,9.529412,62693.634500,NaN,3.92000,NaN,NaN,2.721519,NaN
std,29.011492,NaN,NaN,NaN,12.320021,NaN,NaN,NaN,NaN,NaN,...,1.401695,13931.954834,6.970325,49824.968958,NaN,2.01349,NaN,NaN,1.339122,NaN
min,7001.000000,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,...,1.000000,488.000000,0.000000,488.000000,NaN,1.00000,NaN,NaN,1.000000,NaN
25%,7025.750000,NaN,NaN,NaN,31.750000,NaN,NaN,NaN,NaN,NaN,...,2.000000,10093.250000,5.000000,20627.400000,NaN,2.00000,NaN,NaN,2.000000,NaN
50%,7050.500000,NaN,NaN,NaN,43.000000,NaN,NaN,NaN,NaN,NaN,...,3.000000,22481.000000,10.000000,53264.400000,NaN,4.00000,NaN,NaN,3.000000,NaN
75%,7075.250000,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,...,4.000000,32862.500000,15.000000,92508.500000,NaN,6.00000,NaN,NaN,4.000000,NaN
max,7100.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,NaN,...,5.000000,49919.000000,20.000000,234840.000000,NaN,7.00000,NaN,NaN,5.000000,NaN

In [ ]:
len(df)

100

In [ ]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [ ]:
df.iloc[:, 0]

0     7001
1     7002
2     7003
3     7004
4     7005
      ...
95    7096
96    7097
97    7098
98    7099
99    7100
Name: Order_ID, Length: 100, dtype: int64

In [ ]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State', 'Category', 'Product', 'Brand', 'Quantity', 'Unit_Price', 'Discount_%', 'Total_Amount', 'Payment_Method', 'Delivery_Days', 'Shipping_Type', 'Order_Status', 'Rating', 'Returned']

In [ ]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
Customer_Name      0
Age                0
Gender             0
City               0
State              0
Category           0
Product            0
Brand              0
Quantity           0
Unit_Price         0
Discount_%        15
Total_Amount       0
Payment_Method     0
Delivery_Days      0
Shipping_Type      0
Order_Status       0
Rating            21
Returned           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Age"].unique()

array([52, 45, 44, 21, 23, 49, 48, 47, 32, 18, 43, 40, 34, 59, 57, 58, 55,
       46, 53, 22, 51, 20, 24, 50, 39, 37, 36, 56, 25, 35, 41, 38, 30, 60,
       42, 31, 28, 54])

In [ ]:
df["Age"].nunique()

38

In [ ]:
df["Age"].value_counts()

Age
43    7
23    6
22    5
59    5
34    5
50    5
32    4
58    4
44    4
49    4
45    4
46    4
57    4
40    3
30    3
18    3
41    3
21    2
39    2
24    2
51    2
53    2
42    2
52    1
48    1
47    1
20    1
55    1
36    1
37    1
35    1
25    1
56    1
38    1
60    1
31    1
28    1
54    1
Name: count, dtype: int64

In [ ]:
df.sample(5)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,...,Quantity,Unit_Price,Discount_%,Total_Amount,Payment_Method,Delivery_Days,Shipping_Type,Order_Status,Rating,Returned
80,7081,2025-07-11,C1080,Marcus Hunt,18,Female,Pune,Maharashtra,Fashion,Jeans,...,1,39583,NaN,39583.0,Net Banking,6,Express,Shipped,5.0,No
8,7009,2026-01-21,C1008,Anthony Harris,23,Male,Nashik,Maharashtra,Home,Chair,...,2,26376,15.0,44839.2,Net Banking,4,Same Day,Cancelled,2.0,No
81,7082,2025-07-28,C1081,Dr. Valerie Garcia,22,Female,Nashik,Maharashtra,Electronics,Mouse,...,1,32781,20.0,26224.8,UPI,7,Express,Shipped,NaN,Yes
73,7074,2025-07-31,C1073,Benjamin Caldwell,23,Male,Indore,Madhya Pradesh,Fashion,Jeans,...,3,30497,10.0,82341.9,Net Banking,7,Standard,Shipped,4.0,Yes
90,7091,2025-09-30,C1090,Christopher Williams,41,Male,Nashik,Maharashtra,Beauty,Perfume,...,1,8718,10.0,7846.2,Net Banking,5,Same Day,Delivered,1.0,Yes

In [ ]:
df.size

2100

In [ ]:
df.ndim

2

In [ ]:
df.memory_usage()

Index             132
Order_ID          800
Order_Date        800
Customer_ID       800
Customer_Name     800
Age               800
Gender            800
City              800
State             800
Category          800
Product           800
Brand             800
Quantity          800
Unit_Price        800
Discount_%        800
Total_Amount      800
Payment_Method    800
Delivery_Days     800
Shipping_Type     800
Order_Status      800
Rating            800
Returned          800
dtype: int64

In [ ]:
df.values

array([[7001, '2025-10-31', 'C1000', ..., 'Shipped', 1.0, 'Yes'],
       [7002, '2026-01-17', 'C1001', ..., 'Delivered', 5.0, 'No'],
       [7003, '2025-07-18', 'C1002', ..., 'Shipped', 1.0, 'Yes'],
       ...,
       [7098, '2026-06-29', 'C1097', ..., 'Delivered', 2.0, 'No'],
       [7099, '2026-02-22', 'C1098', ..., 'Cancelled', 5.0, 'Yes'],
       [7100, '2025-08-21', 'C1099', ..., 'Shipped', nan, 'Yes']],
      dtype=object)

In [ ]:
df.sort_values(by="Order_Date")

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,...,Quantity,Unit_Price,Discount_%,Total_Amount,Payment_Method,Delivery_Days,Shipping_Type,Order_Status,Rating,Returned
93,7094,2025-07-11,C1093,Adrian Quinn,57,Male,Nagpur,Maharashtra,Home,Table,...,4,13952,20.0,44646.40,Cash,3,Standard,Shipped,2.0,No
80,7081,2025-07-11,C1080,Marcus Hunt,18,Female,Pune,Maharashtra,Fashion,Jeans,...,1,39583,NaN,39583.00,Net Banking,6,Express,Shipped,5.0,No
39,7040,2025-07-14,C1039,Veronica Boyer,50,Male,Nagpur,Maharashtra,Electronics,Keyboard,...,4,5797,15.0,19709.80,Card,5,Standard,Delivered,3.0,Yes
2,7003,2025-07-18,C1002,Benjamin Davis,44,Male,Nagpur,Maharashtra,Electronics,Mouse,...,1,36781,5.0,34941.95,UPI,5,Express,Shipped,1.0,Yes
14,7015,2025-07-19,C1014,Pamela Berry,34,Female,Nagpur,Maharashtra,Beauty,Shampoo,...,1,9744,0.0,9744.00,Card,5,Standard,Shipped,5.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,7054,2026-06-16,C1053,Carolyn Martinez,59,Female,Pune,Maharashtra,Electronics,Laptop,...,4,29847,20.0,95510.40,Net Banking,1,Same Day,Shipped,2.0,No
38,7039,2026-06-18,C1038,Bridget Daniels,39,Female,Nagpur,Maharashtra,Fashion,Jeans,...,4,537,10.0,1933.20,Card,1,Express,Shipped,3.0,Yes
5,7006,2026-06-27,C1005,Scott Roberts,49,Female,Pune,Maharashtra,Electronics,Monitor,...,2,49919,10.0,89854.20,UPI,6,Standard,Cancelled,3.0,No
97,7098,2026-06-29,C1097,Ronnie Mann,58,Female,Indore,Madhya Pradesh,Electronics,Laptop,...,2,10088,10.0,18158.40,Net Banking,5,Express,Delivered,2.0,No
77,7078,2026-07-02,C1077,Candice Reynolds,50,Male,Pune,Maharashtra,Fashion,Jeans,...,1,26256,10.0,23630.40,UPI,6,Express,Delivered,1.0,Yes